language: node_js
dist: trusty
sudo: required
cache: yarn
node_js:
  - 7.9
services:
  - mongodb
install:
  - npm install bower pulp purescript -g
  - bower install
  - yarn
before_script:
  - sleep 15
  - mongo purescript-node-mongodb-test --eval "show dbs"
script:
  - purs --version
  - pulp test
